from fastapi import APIRouter
from pydantic import BaseModel
from typing import List
import pickle
import pandas as pd

router = APIRouter()

# Load model dan data
with open('app/models/model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

symptomList = ['itching', 'skin_rash', 'nodal_skin_eruptions',
               'continuous_sneezing', 'shivering', 'chills', 'joint_pain',
               'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting',
               'vomiting', 'burning_micturition', 'spotting_ urination',
               'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets',
               'mood_swings', 'weight_loss', 'restlessness', 'lethargy',
               'patches_in_throat', 'irregular_sugar_level', 'cough',
               'high_fever', 'sunken_eyes', 'breathlessness', 'sweating',
               'dehydration', 'indigestion', 'headache', 'yellowish_skin',
               'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes',
               'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea',
               'mild_fever', 'yellow_urine', 'yellowing_of_eyes',
               'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach',
               'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision',
               'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure',
               'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs',
               'fast_heart_rate', 'pain_during_bowel_movements',
               'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus',
               'neck_pain', 'dizziness', 'cramps', 'bruising', 'obesity',
               'swollen_legs', 'swollen_blood_vessels', 'puffy_face_and_eyes',
               'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties',
               'excessive_hunger', 'extra_marital_contacts',
               'drying_and_tingling_lips', 'slurred_speech', 'knee_pain',
               'hip_joint_pain', 'muscle_weakness', 'stiff_neck',
               'swelling_joints', 'movement_stiffness', 'spinning_movements',
               'loss_of_balance', 'unsteadiness', 'weakness_of_one_body_side',
               'loss_of_smell', 'bladder_discomfort', 'foul_smell_of urine',
               'continuous_feel_of_urine', 'passage_of_gases', 'internal_itching',
               'toxic_look_(typhos)', 'depression', 'irritability', 'muscle_pain',
               'altered_sensorium', 'red_spots_over_body', 'belly_pain',
               'abnormal_menstruation', 'dischromic _patches',
               'watering_from_eyes', 'increased_appetite', 'polyuria',
               'family_history', 'mucoid_sputum', 'rusty_sputum',
               'lack_of_concentration', 'visual_disturbances',
               'receiving_blood_transfusion', 'receiving_unsterile_injections',
               'coma', 'stomach_bleeding', 'distention_of_abdomen',
               'history_of_alcohol_consumption', 'fluid_overload.1',
               'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations',
               'painful_walking', 'pus_filled_pimples', 'blackheads', 'scurring',
               'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails',
               'inflammatory_nails', 'blister', 'red_sore_around_nose',
               'yellow_crust_ooze']

symptoms_translation = {
    "ruam kulit": "skin_rash",
    "benjolan pada kulit": "nodal_skin_eruptions",
    "bersin terus-menerus": "continuous_sneezing",
    "menggigil": "shivering",
    "kedinginan": "chills",
    "nyeri sendi": "joint_pain",
    "sakit perut": "stomach_pain",
    "asam lambung": "acidity",
    "luka pada lidah": "ulcers_on_tongue",
    "penyusutan otot": "muscle_wasting",
    "muntah": "vomiting",
    "nyeri saat buang air kecil": "burning_micturition",
    "bercak darah saat buang air kecil": "spotting_ urination",
    "kelelahan": "fatigue",
    "penambahan berat badan": "weight_gain",
    "kecemasan": "anxiety",
    "tangan dan kaki dingin": "cold_hands_and_feets",
    "perubahan suasana hati": "mood_swings",
    "penurunan berat badan": "weight_loss",
    "gelisah": "restlessness",
    "lesu": "lethargy",
    "bercak di tenggorokan": "patches_in_throat",
    "kadar gula tidak normal": "irregular_sugar_level",
    "batuk": "cough",
    "demam tinggi": "high_fever",
    "mata cekung": "sunken_eyes",
    "sesak napas": "breathlessness",
    "berkeringat": "sweating",
    "dehidrasi": "dehydration",
    "gangguan pencernaan": "indigestion",
    "sakit kepala": "headache",
    "kulit menguning": "yellowish_skin",
    "urine berwarna gelap": "dark_urine",
    "mual": "nausea",
    "kehilangan nafsu makan": "loss_of_appetite",
    "nyeri di belakang mata": "pain_behind_the_eyes",
    "sakit punggung": "back_pain",
    "sembelit": "constipation",
    "nyeri perut": "abdominal_pain",
    "diare": "diarrhoea",
    "demam ringan": "mild_fever",
    "urine berwarna kuning": "yellow_urine",
    "mata menguning": "yellowing_of_eyes",
    "gagal hati akut": "acute_liver_failure",
    "kelebihan cairan": "fluid_overload",
    "pembengkakan perut": "swelling_of_stomach",
    "pembengkakan kelenjar getah bening": "swelled_lymph_nodes",
    "malaise": "malaise",
    "penglihatan kabur dan terdistorsi": "blurred_and_distorted_vision",
    "dahak": "phlegm",
    "iritasi tenggorokan": "throat_irritation",
    "kemerahan pada mata": "redness_of_eyes",
    "tekanan sinus": "sinus_pressure",
    "hidung meler": "runny_nose",
    "sesak": "congestion", 
    "nyeri dada": "chest_pain",
    "kelemahan pada anggota tubuh": "weakness_in_limbs",
    "detak jantung cepat": "fast_heart_rate",
    "nyeri saat buang air besar": "pain_during_bowel_movements",
    "nyeri pada daerah anus": "pain_in_anal_region",
    "tinja berdarah": "bloody_stool",
    "iritasi pada anus": "irritation_in_anus",
    "nyeri leher": "neck_pain",
    "pusing": "dizziness",
    "kram": "cramps",
    "memar": "bruising",
    "obesitas": "obesity",
    "pembengkakan kaki": "swollen_legs",
    "pembengkakan pembuluh darah": "swollen_blood_vessels",
    "wajah dan mata bengkak": "puffy_face_and_eyes",
    "pembesaran kelenjar tiroid": "enlarged_thyroid",
    "kuku rapuh": "brittle_nails",
    "pembengkakan ekstremitas": "swollen_extremeties",
    "rasa lapar berlebihan": "excessive_hunger",
    "hubungan di luar nikah": "extra_marital_contacts",
    "kering dan kesemutan pada bibir": "drying_and_tingling_lips",
    "bicara tidak jelas": "slurred_speech",
    "nyeri lutut": "knee_pain",
    "nyeri sendi pinggul": "hip_joint_pain",
    "kelemahan otot": "muscle_weakness",
    "kekakuan leher": "stiff_neck",
    "pembengkakan sendi": "swelling_joints",
    "kekakuan gerakan": "movement_stiffness",
    "gerakan berputar": "spinning_movements",
    "kehilangan keseimbangan": "loss_of_balance",
    "ketidakstabilan": "unsteadiness",
    "kelemahan pada satu sisi tubuh": "weakness_of_one_body_side",
    "kehilangan penciuman": "loss_of_smell",
    "ketidaknyamanan kandung kemih": "bladder_discomfort",
    "bau urine tidak sedap": "foul_smell_of urine",
    "perasaan ingin berkemih terus-menerus": "continuous_feel_of_urine",
    "keluarnya gas": "passage_of_gases",
    "gatal-gatal di dalam": "internal_itching",
    "penampilan toksik (demam tifoid)": "toxic_look_(typhos)",
    "depresi": "depression",
    "mudah tersinggung": "irritability",
    "nyeri otot": "muscle_pain",
    "persepsi sensorik yang berubah": "altered_sensorium",
    "bintik merah di seluruh tubuh": "red_spots_over_body",
    "nyeri perut": "belly_pain",
    "menstruasi tidak normal": "abnormal_menstruation",
    "noda dischromic": "dischromic _patches",
    "air mata dari mata": "watering_from_eyes",
    "nafsu makan meningkat": "increased_appetite",
    "poliuria": "polyuria",
    "riwayat keluarga": "family_history",
    "lendir dalam dahak": "mucoid_sputum",
    "dahak berkarat": "rusty_sputum",
    "kurangnya konsentrasi": "lack_of_concentration",
    "gangguan penglihatan": "visual_disturbances",
    "menerima transfusi darah": "receiving_blood_transfusion",
    "menerima suntikan tidak steril": "receiving_unsterile_injections",
    "koma": "coma",
    "pendarahan perut": "stomach_bleeding",
    "perut membesar": "distention_of_abdomen",
    "riwayat konsumsi alkohol": "history_of_alcohol_consumption",
    "kelebihan cairan": "fluid_overload.1", 
    "darah dalam dahak": "blood_in_sputum", 
    "pembuluh darah menonjol di betis": "prominent_veins_on_calf",
    "palpitasi": "palpitations",
    "nyeri saat berjalan": "painful_walking",
    "jerawat bernanah": "pus_filled_pimples",
    "komedo": "blackheads",
    "keloid": "scurring",
    "kulit mengelupas": "skin_peeling",
    "kekasaran kulit": "silver_like_dusting",
    "cekungan kecil pada kuku": "small_dents_in_nails",
    "kuku meradang": "inflammatory_nails",
    "lepuh": "blister",
    "luka merah di sekitar hidung": "red_sore_around_nose",
    "kerak kuning yang mengeluarkan nanah": "yellow_crust_ooze"
}

disease = ['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne',
           'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
           'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
           'Common Cold', 'Dengue', 'Diabetes ',
           'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
           'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack',
           'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
           'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
           'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
           'Osteoarthristis', 'Paralysis (brain hemorrhage)',
           'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
           'Typhoid', 'Urinary tract infection', 'Varicose veins',
           'hepatitis A']

disease_translation = {
    "Paroymsal  Positional Vertigo": "Vertigo (vertigo) Paroymsal Positional Vertigo",
    "AIDS": "AIDS",
    "Acne": "Jerawat",
    "Alcoholic hepatitis": "Hepatitis alkoholik",
    "Allergy": "Alergi",
    "Arthritis": "Artritis",
    "Bronchial Asthma": "Asma bronkial",
    "Cervical spondylosis": "Spondilosis serviks",
    "Chicken pox": "Cacar air",
    "Chronic cholestasis": "Kolesistitis kronis",
    "Common Cold": "Flu biasa",
    "Dengue": "Dengue",
    "Diabetes": "Diabetes",
    "Dimorphic hemmorhoids(piles)": "Hemoroid dimorfik (wasir)",
    "Drug Reaction": "Reaksi obat",
    "Fungal infection": "Infeksi jamur",
    "GERD": "GERD",
    "Gastroenteritis": "Gastroenteritis",
    "Heart attack": "Serangan jantung",
    "Hepatitis B": "Hepatitis B",
    "Hepatitis C": "Hepatitis C",
    "Hepatitis D": "Hepatitis D",
    "Hepatitis E": "Hepatitis E",
    "Hypertension": "Hipertensi",
    "Hyperthyroidism": "Hipertiroidisme",
    "Hypoglycemia": "Hipoglikemia",
    "Hypothyroidism": "Hipotiroidisme",
    "Impetigo": "Impetigo",
    "Jaundice": "Penyakit kuning",
    "Malaria": "Malaria",
    "Migraine": "Migrain",
    "Osteoarthristis": "Osteoartritis",
    "Paralysis (brain hemorrhage)": "Paralisis (pendarahan otak)",
    "Peptic ulcer diseae": "Penyakit tukak lambung",
    "Pneumonia": "Pneumonia",
    "Psoriasis": "Psoriasis",
    "Tuberculosis": "Tuberkulosis",
    "Typhoid": "Tifus",
    "Urinary tract infection": "Infeksi saluran kemih",
    "Varicose veins": "Varises",
    "hepatitis A": "hepatitis A"
}
class Symptomclass(BaseModel):
    symptoms: List[str]
@router.post("/predict")
def func(s: Symptomclass):
    # Terjemahkan gejala dari Bahasa Indonesia ke Bahasa Inggris
    translated_symptoms = [symptoms_translation.get(gejala, None) for gejala in s.symptoms]
    translated_symptoms = [s for s in translated_symptoms if s is not None]  # Filter gejala tidak dikenali

    # Buat input model
    input = [1 if i in translated_symptoms else 0 for i in symptomList]
    input_df = pd.DataFrame([input], columns=symptomList)

    # Prediksi
    prediction_index = int(loaded_model.predict(input_df))
    pred_en = disease[prediction_index]
    pred_id = disease_translation.get(pred_en, pred_en)

    # Ambil confidence
    proba = loaded_model.predict_proba(input_df)[0]
    confidence = proba[prediction_index] * 100  # persen

    return {
        "disease_en": pred_en,
        "disease_id": pred_id,
        "confidence": round(confidence, 2)
    }


# Commenting out for vercel deploymnt
# if __name__ == "__main__":
#     uvicorn.run(app, host="0.0.0.0", port=3004)
